# Generated by Django 4.1.7 on 2023-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iframe_id', models.PositiveIntegerField()),
                ('integration_id', models.PositiveIntegerField()),
                ('api_key', models.TextField(max_length=512)),
                ('hmac_secret', models.TextField(max_length=512)),
                ('currency', models.CharField(default='EGP', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('web_hook_secret', models.CharField(max_length=1024)),
                ('publishable_key', models.CharField(max_length=1024)),
                ('secret_key', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
