# Generated by Django 4.1.7 on 2023-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ltr', models.BooleanField(default=True)),
                ('lang', models.CharField(choices=[('en', 'En'), ('ar', 'Ar')], max_length=6)),
                ('text', models.TextField(max_length=5048)),
            ],
        ),
    ]
