# Generated by Django 4.1.7 on 2023-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(blank=True, max_length=5048, null=True),
        ),
    ]
