# Generated by Django 4.1.7 on 2023-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_transaction_id_refund_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='payment_intent',
        ),
    ]
