# Generated by Django 4.1.7 on 2023-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_refund_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='payment_intent',
            field=models.CharField(default=21414, max_length=256),
            preserve_default=False,
        ),
    ]
