# Generated by Django 4.1.7 on 2023-08-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_icon_alter_categorybanner_content'),
        ('product', '0002_productbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
