# Generated by Django 4.1.7 on 2023-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
