# Generated by Django 4.1.7 on 2023-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('product', '0005_alter_productbanner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='button_text',
            field=models.ManyToManyField(blank=True, related_name='product_banner_button_text_set', to='translations.translation'),
        ),
        migrations.AddField(
            model_name='productbanner',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
