# Generated by Django 4.1.7 on 2023-08-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('page', '0001_initial'),
        ('product', '0008_delete_productbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=64)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('redirect_url', models.URLField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.carousel')),
                ('content', models.ManyToManyField(blank=True, related_name='product_banner_content_set', to='translations.translation')),
                ('sub_title', models.ManyToManyField(blank=True, related_name='product_banner_sub_title_set', to='translations.translation')),
                ('title', models.ManyToManyField(blank=True, related_name='product_banner_title_set', to='translations.translation')),
            ],
        ),
    ]
