# Generated by Django 4.1.7 on 2023-09-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_carousel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
