# Generated by Django 4.1.7 on 2023-09-17 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_banner_redirect_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='variantattribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variantattribute')),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.attributevalue'),
        ),
    ]
