# Generated by Django 4.1.7 on 2023-09-18 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_remove_sku_extra_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantAttribute',
            new_name='Attribute',
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_value_set', to='product.attribute'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_image_set', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_set', to='product.product'),
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_wish_set', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisth_item_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
