# Generated by Django 4.1.7 on 2023-09-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_variantattribute_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_attribute_set', to='product.attribute')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_set', to='product.productvariant')),
            ],
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_value_set', to='product.attribute'),
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_attribute_set', to='product.attributevalue'),
        ),
    ]
