# Generated by Django 4.1.7 on 2023-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_variantattribute_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='slug',
        ),
        migrations.AddField(
            model_name='banner',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
