# Generated by Django 4.1.7 on 2023-09-21 13:22

from django.db import migrations
import product.models.variant_images
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_banner_slug_banner_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product_image',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to='', validators=[utils.fields.LimitedImageField.validate_max_size, utils.fields.LimitedImageField.validate_max_size]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='thumbnail',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to='', validators=[utils.fields.LimitedImageField.validate_max_size, utils.fields.LimitedImageField.validate_max_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=utils.fields.LimitedImageField(upload_to=product.models.variant_images.product_image_handler, validators=[utils.fields.LimitedImageField.validate_max_size, utils.fields.LimitedImageField.validate_max_size]),
        ),
    ]
