# Generated by Django 4.1.7 on 2023-09-25 13:36

from django.db import migrations
import product.models.variant_images
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_banner_product_image_alter_banner_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product_image',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='banner',
            name='thumbnail',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_image',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=utils.fields.LimitedImageField(upload_to=product.models.variant_images.product_image_handler),
        ),
    ]
