# Generated by Django 4.1.7 on 2023-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_currency_code',
            field=models.CharField(default='usd', max_length=9),
            preserve_default=False,
        ),
    ]
