# Generated by Django 4.1.7 on 2023-09-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('PLACED', 'Placed'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='Processing', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Pending', 'Pending'), ('Partially Refunded', 'Partially Refunded'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('CANCELLED', 'Cancelled'), ('Processing', 'Processing')], default='Pending', max_length=64),
        ),
    ]
