# Generated by Django 4.1.7 on 2023-07-23 08:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=24, unique=True)),
                ('section_type', models.CharField(choices=[('Page', 'Page'), ('SECTION', 'Section')], max_length=16)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'En'), ('ar', 'Ar')], max_length=6, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'En'), ('ar', 'Ar')], max_length=6, null=True)),
                ('title', models.CharField(max_length=64)),
                ('title_type', models.IntegerField(choices=[(0, 'Title'), (1, 'Sub title')])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='content_set', to='page.sectioncontent'),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.ManyToManyField(blank=True, related_name='description_set', to='page.sectioncontent'),
        ),
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_section_set', to='page.section'),
        ),
    ]
