# Generated by Django 4.1.7 on 2023-09-19 15:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
