# Generated by Django 4.1.7 on 2023-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency_code',
            field=models.CharField(default='23', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='currency_factor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='currency_name',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='currency_symbol',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
    ]
