# Generated by Django 4.1.7 on 2023-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_currency_code_client_currency_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='minimum_order_price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
