# Generated by Django 4.1.7 on 2023-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_client_minimum_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_purchase',
            field=models.BooleanField(default=True),
        ),
    ]
