# Generated by Django 4.1.7 on 2023-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_client_allow_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
