# Generated by Django 4.1.7 on 2023-08-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_client_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='currency_factor',
        ),
    ]
