# Generated by Django 4.1.7 on 2023-09-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_client_currency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
