# Generated by Django 4.1.7 on 2023-10-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='minimum_order_price',
        ),
    ]
