# Generated by Django 4.1.7 on 2023-07-26 09:11

import category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('translations', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=category.models.category_img_handler)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('content', models.ManyToManyField(to='translations.translation')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryBannder',
        ),
    ]
