# Generated by Django 4.1.7 on 2023-07-26 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('category', '0002_categorybanner_delete_categorybannder'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='categorybanner',
            name='content',
            field=models.ManyToManyField(blank=True, to='translations.translation'),
        ),
    ]
