# Generated by Django 4.1.7 on 2023-08-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('category', '0003_category_icon_alter_categorybanner_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybanner',
            name='button_text',
            field=models.ManyToManyField(blank=True, related_name='category_banner_button_text_set', to='translations.translation'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='sub_title',
            field=models.ManyToManyField(blank=True, related_name='category_banner_sub_title_set', to='translations.translation'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='title',
            field=models.ManyToManyField(blank=True, related_name='category_banner_title_set', to='translations.translation'),
        ),
        migrations.AlterField(
            model_name='categorybanner',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='category_banner_content_set', to='translations.translation'),
        ),
        migrations.AlterField(
            model_name='categorybanner',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
