# Generated by Django 4.1.7 on 2023-08-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_categorybanner_button_text_categorybanner_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryBanner',
        ),
    ]
