# Generated by Django 4.1.7 on 2023-08-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('category', '0005_delete_categorybanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_location', models.CharField(choices=[('primary_menu', 'Primary Menu'), ('footer_column_1', 'Footer Column 1'), ('footer_column_2', 'Footer Column 2'), ('footer_column_3', 'Footer Column 3'), ('footer_column_4', 'Footer Column 4'), ('footer_column_5', 'Footer Column 5'), ('footer_copy_right', 'Footer Copy Right')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('names', models.ManyToManyField(to='translations.translation')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.URLField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_menu_item_set', to='category.category')),
                ('labels', models.ManyToManyField(to='translations.translation')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_set', to='category.menu')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_subitem_set', to='category.menuitem')),
            ],
        ),
    ]
