# Generated by Django 4.1.7 on 2023-08-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('category', '0007_menuitem_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='names',
            field=models.ManyToManyField(blank=True, to='translations.translation'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='labels',
            field=models.ManyToManyField(blank=True, to='translations.translation'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_subitem_set', to='category.menuitem'),
        ),
    ]
