# Generated by Django 4.1.7 on 2023-08-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_menu_names_alter_menuitem_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='path',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
