# Generated by Django 4.1.7 on 2023-09-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_menuitem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='display_location',
            field=models.CharField(choices=[('primary_menu', 'Primary Menu'), ('footer_column_1', 'Footer Column 1'), ('footer_column_2', 'Footer Column 2'), ('footer_column_3', 'Footer Column 3'), ('footer_column_4', 'Footer Column 4'), ('footer_column_5', 'Footer Column 5'), ('topbar_1', 'Topbar 1'), ('topbar_2', 'Topbar 2'), ('topbar_3', 'Topbar 3'), ('footer_copy_right_1', 'Footer Copy Right 1'), ('footer_copy_right_2', 'Footer Copy Right 2'), ('footer_copy_right_3', 'Footer Copy Right 3')], max_length=32),
        ),
    ]
