# Generated by Django 4.1.7 on 2023-09-25 09:13

import category.models.category
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to=category.models.category.category_img_handler, validators=[utils.fields.LimitedImageField.validate_max_size, utils.fields.LimitedImageField.validate_max_size]),
        ),
    ]
