# Generated by Django 4.1.7 on 2023-09-25 13:36

import category.models.category
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to=category.models.category.category_img_handler),
        ),
    ]
