# Generated by Django 4.1.7 on 2023-07-27 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0001_initial'),
        ('product', '0002_productbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='venderrating',
            unique_together={('user', 'vender')},
        ),
    ]
