# Generated by Django 4.1.7 on 2023-08-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='parent_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.region'),
        ),
    ]
