# Generated by Django 4.1.7 on 2023-09-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_shipmentprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('VERIFY', 'Verify'), ('RESET', 'Reset'), ('ACTIVATE', 'Activate')], default='ACTIVATE', max_length=16),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
