# Generated by Django 4.1.7 on 2023-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_shipmentprofile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentprofile',
            name='address',
            field=models.CharField(default='default value', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipmentprofile',
            name='apartment',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprofile',
            name='building',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprofile',
            name='floor',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
