# Generated by Django 4.1.7 on 2023-09-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_shipmentprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentprofile',
            old_name='city',
            new_name='region',
        ),
    ]
