# Generated by Django 4.1.7 on 2023-09-21 13:22

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_city_shipmentprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to='', validators=[utils.fields.LimitedImageField.validate_max_size, utils.fields.LimitedImageField.validate_max_size]),
        ),
    ]
