# Generated by Django 4.1.7 on 2023-09-24 06:03

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='object',
            field=models.CharField(default='asfaf', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='verify_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=utils.fields.LimitedImageField(blank=True, null=True, upload_to='', validators=[utils.fields.LimitedImageField.validate_max_size, utils.fields.LimitedImageField.validate_max_size]),
        ),
    ]
