# Generated by Django 4.1.7 on 2023-09-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_phone_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
