# Generated by Django 4.1.7 on 2023-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_region_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentprofile',
            name='street',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
