# Generated by Django 4.1.7 on 2023-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_shipmentprofile_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='shipment_price',
            field=models.FloatField(default=0),
        ),
    ]
