# Generated by Django 4.1.7 on 2023-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_region_shipment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='fixed_shipment_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='minimum_order_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
