# Generated by Django 4.1.7 on 2023-10-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_region_fixed_shipment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='minimum_order_free_ship_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
